### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by souovan** [souovan/nextcloud_home_server#1]
- [ ] implement full configuration with makefile
- [ ] implement full installation with makefile
- [ ] implement uninstallation with makefile
